apiVersion: v1
kind: ConfigMap
metadata:
  name: auth
  namespace: gitlab
data:
  htpasswd: |
    registry:$2y$05$4X/WhX3DzFApAff/41tbtuXhgP.dB/6xkP6XSzTQhtH14TsmKFR4y
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: registry
  namespace: gitlab
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - image: mav96/scaleway_registry
        name: registry
        imagePullPolicy: Always
        env:
        - name: REGISTRY_LOG_LEVEL
          value: debug
        - name: REGISTRY_HTTP_ADDR
          value: :5000
        - name: REGISTRY_HTTP_DEBUG_ADDR
          value: :5001
        - name: REGISTRY_STORAGE
          value: s3
        - name: REGISTRY_STORAGE_S3_ACCESSKEY
          value: "ACCESSKEY"
        - name: REGISTRY_STORAGE_S3_SECRETKEY
          value: "SECRETKEY"
        - name: REGISTRY_STORAGE_S3_REGION
          value: "nl-ams"
        - name: REGISTRY_STORAGE_S3_REGIONENDPOINT
          value: "https://s3.nl-ams.scw.cloud"
        - name: REGISTRY_STORAGE_S3_BUCKET
          value: "docker-registry"
        - name: REGISTRY_STORAGE_S3_SECURE
          value: "false"
        - name: REGISTRY_STORAGE_CACHE_BLOBDESCRIPTOR
          value: inmemory
        - name: REGISTRY_AUTH
          value: htpasswd
        - name: REGISTRY_HTTP_SECRET
          value: "dockerdocker"
        - name: REGISTRY_AUTH_HTPASSWD_REALM
          value: "basic-realm"
        - name: REGISTRY_AUTH_HTPASSWD_PATH
          value: "/auth/htpasswd"
        ports:
        - containerPort: 5000
        volumeMounts:
          - name: auth
            mountPath: /auth
      volumes:
        - name: auth
          configMap:
            name: auth
            items:
            - key: htpasswd
              path: htpasswd

---
apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: gitlab
  labels:
    name: registry
spec:
  ports:
  - protocol: TCP
    port: 5000
    name: internal
  selector:
    app: registry
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: registry
  namespace: gitlab
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: registry.k8s.selit.ru
    http:
      paths:
      - path: /
        backend:
          serviceName: registry
          servicePort: 5000              
